### PR TITLE
Providing a protocol for the cache to implement

### PR DESCRIPTION
**Pull request by oliyh**
Hello,

This change provides a protocol for interaction with the cache, allowing potentially different implementations with non-functional features like TTL, distribution etc and allowing the developer to introspect the cache without being tied to urania implementation.

Hope this makes sense and fits with the design principles of urania.

Thanks
Oliy

### CODE REVIEW

**Comment by oliyh** [comment]
Ping @dialelo

**Comment by txus** [comment]
+1 :)

**Comment by dialelo** [comment]
This is great @oliyh, thanks a lot for your time. Will add some docs about using custom cache implementations and cut a new release with these changes.

**Comment by dialelo** [comment]
I need to do some changes into how cached results are injected into the urania AST, since assumes a cache with an infinite TTL 😊 Working on it.

**Comment by oliyh** [comment]
Great, thanks @dialelo! Looking forward to the new release.

**Comment by oliyh** [comment]
@dialelo I was thinking about what you said and presume you mean how the cache will behave within one run. I think assuming an infinite TTL is better because that will guarantee consistent results in one run for a given muse. If you don't have that it could get very confusing.

One of the main features I wanted to achieve from this change was a read-through cache (backed by redis). We decided that the read from redis should happen a maximum of once per run to make all results consistent.

**Comment by oliyh** [comment]
Hi @dialelo,

Did you have a chance to look at this yet? Appreciate you have other uses of your time but this would be really useful to us.

Cheers
Oliy

**Comment by oliyh** [comment]
@jespino or @niwinz would you be able to comment on the state of the urania project? Will it be maintained?

Cheers

**Pull request merged**
